name: farmer_app
description: A farmer's recommendation app.

# Add this environment section:
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^0.13.6
  http_parser: ^4.0.0
  flutter_sound: ^9.2.13
  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  intl: ^0.17.0
  image_picker: ^0.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# Fonts, assets, etc. can be added here as needed
flutter:
  uses-material-design: true
  assets:
    - assets/images/farmer_icon.jpg


